useDotenv: true
service: serverless-crud

provider:
  name: aws
  runtime: nodejs12.x
  # region: ap-northeast-1
  region: us-east-1
  stage: dev
  iamRoleStatements: ${file(./config/iam.yml)}

functions:

  boxAll:
    handler: handler.boxAll
    events:
      - http:
          path: boxstatus
          method: get
          cors: true

  boxUp:
    handler: handler.boxUp
    events:
      - http:
          path: boxstatus
          method: post
          cors: true

  lineRes:
    handler: handler.lineRes
    events:
      - http:
          path: todos2
          method: post
          cors: true

  create:
    handler: handler.create
    events:
      - http:
          path: todos
          method: post
          cors: true
  readAll:
    handler: handler.readAll
    events:
      - http:
          path: todos
          method: get
          cors: true
  readOne:
    handler: handler.readOne
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true


resources:
  - ${file(./config/s3.yml)}
  - ${file(./config/dynamodb.yml)}
  - ${file(./config/dynamodb2.yml)}
  - ${file(./config/dynamodb3.yml)}

plugins:
  - serverless-s3-sync

custom:
  webSiteName: web0316
  s3Sync:
    - bucketName: ${self:custom.webSiteName}
      localDir: static
